version: '3.7'

services:
  ofbiz:
    container_name: ofbiz-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./:/ofbiz  # Volume mount to allow runtime changes to xml etc.
    networks:
      - ofbiz-api-network
      - db-network

networks:
  ofbiz-api-network:
    name: ofbiz-api-network
    driver: bridge
  db-network:
    external:
      name: db-network
